#!/usr/bin/env python3
"""Expand testvectors/vectors.json into vectors_gen_test.mbt.

The JSON file is the source of truth shared by ports of moon-scrub to other
languages. Each vector names an input, a scanning mode, and the findings that
must be reported: kind, matched literal, and confidence. This script resolves
literals to UTF-16 start/end offsets, verifies each literal occurs exactly
once, and emits a MoonBit test block per vector.

Usage:
  python3 scripts/gen_vectors.py            # regenerate vectors_gen_test.mbt
  python3 scripts/gen_vectors.py --check    # exit 1 if the file is stale
"""

import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
VECTORS = ROOT / "testvectors" / "vectors.json"
TARGET = ROOT / "vectors_gen_test.mbt"

CONFIDENCE = {"HIGH": "@moon_scrub.High", "MEDIUM": "@moon_scrub.Medium"}


def utf16_len(text: str) -> int:
    return len(text.encode("utf-16-le")) // 2


def moonbit_escape(text: str) -> str:
    out = []
    for ch in text:
        if ch == '"':
            out.append('\\"')
        elif ch == "\\":
            out.append("\\\\")
        elif ch == "\n":
            out.append("\\n")
        elif ch == "\t":
            out.append("\\t")
        elif ch == "\r":
            out.append("\\r")
        elif ord(ch) < 0x20:
            out.append(f"\\u{ord(ch):04x}")
        else:
            out.append(ch)
    return "".join(out)


def resolve(vector) -> None:
    """Attach absolute UTF-16 offsets to each expected finding."""
    input_text = vector["input"]
    for expect in vector["expect"]:
        literal = expect["literal"]
        first = input_text.find(literal)
        if first < 0:
            raise SystemExit(f"vector {vector['name']!r}: literal not found: {literal!r}")
        if input_text.find(literal, first + 1) >= 0:
            raise SystemExit(f"vector {vector['name']!r}: literal not unique: {literal!r}")
        expect["start"] = utf16_len(input_text[:first])
        expect["end"] = expect["start"] + utf16_len(literal)


def call_expr(indent: str, head: str, args: list) -> str:
    """Format a call on one line, or wrapped the way `moon fmt` wraps it."""
    single = f"{indent}{head}({', '.join(args)})"
    if len(single) <= 80:
        return single
    lines = [f"{indent}{head}("]
    for arg in args:
        lines.append(f"{indent}  {arg},")
    lines.append(f"{indent})")
    return "\n".join(lines)


def emit(doc) -> str:
    lines = [
        "///|",
        "// Generated by scripts/gen_vectors.py from testvectors/vectors.json.",
        "// Do not edit by hand; regenerate with the script after changing vectors.",
        "",
    ]
    for vector in doc["vectors"]:
        mode = vector["mode"]
        if mode == "phone":
            # moon fmt wraps a struct-literal argument in its own shape;
            # emit that shape directly so --check and fmt agree.
            scan_call = "\n".join([
                "  let findings = @moon_scrub.scan_with_config(input, {",
                "    ..@moon_scrub.ScanConfig::standard(),",
                "    detect_phone: true,",
                "  })",
            ])
        elif mode == "config":
            scan_call = call_expr(
                "  ",
                "let findings = @moon_scrub.scan_with_config",
                ["input", "@moon_scrub.ScanConfig::standard()"],
            )
        elif mode == "secrets":
            scan_call = call_expr(
                "  ",
                "let findings = @moon_scrub.scan",
                ["input", "policy=@moon_scrub.ScanPolicy::secrets_only()"],
            )
        else:
            scan_call = call_expr(
                "  ", "let findings = @moon_scrub.scan", ["input"]
            )
        lines.append("///|")
        lines.append(f'test "vector: {vector["name"]}" {{')
        lines.append(f'  let input = "{moonbit_escape(vector["input"])}"')
        lines.append(scan_call)
        lines.append(f"  assert_eq(findings.length(), {len(vector['expect'])})")
        for index, expect in enumerate(vector["expect"]):
            confidence = CONFIDENCE[expect["confidence"]]
            lines.append(f'  assert_eq(findings[{index}].kind.to_string(), "{expect["kind"]}")')
            lines.append(f"  assert_eq(findings[{index}].start, {expect['start']})")
            lines.append(f"  assert_eq(findings[{index}].end, {expect['end']})")
            lines.append(f"  assert_eq(findings[{index}].confidence, {confidence})")
            lines.append(
                call_expr(
                    "  ",
                    "assert_eq",
                    [
                        f"input[findings[{index}].start:findings[{index}].end].to_owned()",
                        f'"{moonbit_escape(expect["literal"])}"',
                    ],
                )
            )
        lines.append("}")
        lines.append("")
    return "\n".join(lines)


def main() -> None:
    doc = json.loads(VECTORS.read_text(encoding="utf-8"))
    for vector in doc["vectors"]:
        resolve(vector)
    content = emit(doc)
    if "--check" in sys.argv:
        current = TARGET.read_text(encoding="utf-8") if TARGET.exists() else ""
        if current != content:
            print("vectors_gen_test.mbt is stale; run scripts/gen_vectors.py")
            sys.exit(1)
        print("vectors_gen_test.mbt is up to date")
        return
    TARGET.write_text(content, encoding="utf-8")
    print(f"wrote {TARGET} ({len(doc['vectors'])} vectors)")


if __name__ == "__main__":
    main()
